"""
PDF Conversion Script for TeachGenie Project Analysis
Converts markdown to PDF with TeachGenie branding and footer
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from datetime import datetime
import re
import os
import sys

class FooterCanvas(canvas.Canvas):
    """Custom canvas with TeachGenie footer"""
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []
        
    def showPage(self):
        self.pages.append(dict(self.__dict__))
        self._startPage()
        
    def save(self):
        page_count = len(self.pages)
        for page_num, page in enumerate(self.pages, 1):
            self.__dict__.update(page)
            self.draw_footer(page_num, page_count)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
        
    def draw_footer(self, page_num, page_count):
        """Draw TeachGenie branded footer on each page"""
        self.saveState()
        self.setFont('Helvetica', 8)
        
        # Footer text
        footer_left = "Generated by TeachGenie Development Team"
        current_time = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        footer_right = current_time
        
        # Draw footer line
        self.setStrokeColor(colors.HexColor('#e74c3c'))
        self.setLineWidth(0.5)
        self.line(0.75 * inch, 0.65 * inch, 7.75 * inch, 0.65 * inch)
        
        # Draw footer text
        self.setFillColor(colors.HexColor('#2c3e50'))
        self.drawString(0.75 * inch, 0.45 * inch, footer_left)
        self.drawRightString(7.75 * inch, 0.45 * inch, footer_right)
        
        # Page number
        self.setFont('Helvetica', 7)
        self.setFillColor(colors.HexColor('#7f8c8d'))
        self.drawCentredString(4.25 * inch, 0.3 * inch, f"Page {page_num} of {page_count}")
        
        self.restoreState()

def clean_markdown_text(text):
    """Clean markdown formatting for PDF"""
    # Bold
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    # Code
    text = re.sub(r'`(.*?)`', r'<font face="Courier" color="#c7254e">\1</font>', text)
    # Links (keep text only)
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    return text

def markdown_to_pdf(markdown_file, output_pdf):
    """Convert markdown to PDF with TeachGenie branding"""
    
    # Read markdown content
    with open(markdown_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Create PDF
    doc = SimpleDocTemplate(
        output_pdf,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=1.1*inch  # Extra space for footer
    )
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles with TeachGenie branding
    title_style = ParagraphStyle(
        'TeachGenieTitle',
        parent=styles['Heading1'],
        fontSize=26,
        textColor=colors.HexColor('#e74c3c'),  # TeachGenie red
        spaceAfter=30,
        spaceBefore=10,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading1_style = ParagraphStyle(
        'TeachGenieH1',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=12,
        spaceBefore=16,
        fontName='Helvetica-Bold',
        borderColor=colors.HexColor('#e74c3c'),
        borderWidth=0,
        borderPadding=5
    )
    
    heading2_style = ParagraphStyle(
        'TeachGenieH2',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#34495e'),
        spaceAfter=10,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    heading3_style = ParagraphStyle(
        'TeachGenieH3',
        parent=styles['Heading3'],
        fontSize=11,
        textColor=colors.HexColor('#7f8c8d'),
        spaceAfter=8,
        spaceBefore=10,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'TeachGenieBody',
        parent=styles['BodyText'],
        fontSize=9,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        fontName='Helvetica',
        leading=12
    )
    
    code_style = ParagraphStyle(
        'TeachGenieCode',
        parent=styles['Code'],
        fontSize=8,
        textColor=colors.HexColor('#2c3e50'),
        backColor=colors.HexColor('#f8f9fa'),
        fontName='Courier',
        leftIndent=20,
        rightIndent=10,
        spaceAfter=8,
        spaceBefore=4,
        borderColor=colors.HexColor('#dee2e6'),
        borderWidth=1,
        borderPadding=8
    )
    
    # Story (content container)
    story = []
    
    # Parse markdown
    lines = content.split('\n')
    in_code_block = False
    in_mermaid = False
    code_buffer = []
    
    for line in lines:
        # Skip mermaid diagrams
        if '```mermaid' in line:
            in_mermaid = True
            continue
        
        if in_mermaid:
            if '```' in line:
                in_mermaid = False
            continue
        
        # Code blocks
        if line.startswith('```'):
            if in_code_block:
                # End code block
                if code_buffer:
                    code_text = '<br/>'.join(code_buffer)
                    story.append(Paragraph(code_text, code_style))
                    code_buffer = []
                in_code_block = False
            else:
                # Start code block
                in_code_block = True
            continue
        
        if in_code_block:
            code_buffer.append(line.replace('<', '&lt;').replace('>', '&gt;'))
            continue
        
        # Headers
        if line.startswith('# '):
            text = line[2:].strip()
            story.append(Paragraph(text, title_style))
            story.append(Spacer(1, 0.15*inch))
        elif line.startswith('## '):
            text = line[3:].strip()
            # Skip emoji icons
            text = re.sub(r'[📋🏗️🔐🤖🗄️🌐💾🎨🔄📦🚀🐛📊🔒📚🎯📞]', '', text).strip()
            story.append(Spacer(1, 0.12*inch))
            story.append(Paragraph(text, heading1_style))
        elif line.startswith('### '):
            text = line[4:].strip()
            text = re.sub(r'[✅🔄]', '', text).strip()
            story.append(Paragraph(text, heading2_style))
        elif line.startswith('#### '):
            text = line[5:].strip()
            story.append(Paragraph(text, heading3_style))
        
        # Horizontal rules
        elif line.strip() == '---':
            story.append(Spacer(1, 0.08*inch))
        
        # Lists
        elif line.strip().startswith('- ') or line.strip().startswith('* '):
            text = line.strip()[2:]
            text = clean_markdown_text(text)
            story.append(Paragraph(f'• {text}', body_style))
        
        # Numbered lists
        elif re.match(r'^\d+\.\s', line.strip()):
            text = re.sub(r'^\d+\.\s', '', line.strip())
            text = clean_markdown_text(text)
            story.append(Paragraph(text, body_style))
        
        # Tables (simple handling)
        elif '|' in line and not line.strip().startswith('|---'):
            text = line.replace('|', ' ')
            text = clean_markdown_text(text)
            if text.strip():
                story.append(Paragraph(text, body_style))
        
        # Regular paragraphs
        elif line.strip() and not line.strip().startswith('|---'):
            text = line.strip()
            text = clean_markdown_text(text)
            
            if text and not text.startswith('```'):
                story.append(Paragraph(text, body_style))
        
        # Empty lines
        else:
            if line.strip() == '':
                story.append(Spacer(1, 0.08*inch))
    
    # Build PDF with custom canvas
    print("Building PDF with TeachGenie branding...")
    doc.build(story, canvasmaker=FooterCanvas)
    print(f"✓ PDF created successfully: {output_pdf}")

if __name__ == "__main__":
    # Determine paths
    if len(sys.argv) > 1:
        markdown_file = sys.argv[1]
        output_pdf = sys.argv[2] if len(sys.argv) > 2 else "output.pdf"
    else:
        # Default paths
        script_dir = os.path.dirname(os.path.abspath(__file__))
        markdown_file = os.path.join(script_dir, "project_analysis.md")
        output_pdf = os.path.join(script_dir, "TeachGenie_Project_Analysis.pdf")
    
    # Convert
    if os.path.exists(markdown_file):
        markdown_to_pdf(markdown_file, output_pdf)
    else:
        print(f"Error: Markdown file not found: {markdown_file}")
        sys.exit(1)
